version: "3.9"
   
services:

  domain_db:
    container_name: domain_db
    hostname: domain_db
    image: postgres
    environment:
      - POSTGRES_DB=domaindb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpass
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    volumes: 
      - ./migrations/:/migrations
    # here instead of localhost as the host we use domain_db as that is the name we gave to the postgres service
    command:
      [ "-path", "/migrations", "-database",  "postgres://postgres:secretpass@domain_db:5432/domaindb?sslmode=disable", "up" ]
    depends_on:
      domain_db:
        condition: service_healthy